project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    # - "*.ipynb"
    - "!aux/"


website:
  title: "Science & Programming"
  site-url: "https://julia-kaeri.github.io/"
  site-path: "/"
  page-navigation: true
  navbar:
    background: primary
    # collapse-below: lg
    left:
      - href: index.qmd
        text: Home
      # - href : https://julia-kaeri.github.io/IntroductionToJulia/
      #   text : "Julia 언어"
      # - href : https://julia-kaeri.github.io/IntroductionToJulia/
      #   text : "수치해석"
      # - href :  src/image_processing/index.qmd
      #   text : "영상 처리/토모그래피"
      - href : src/topics/qmd
        text : 주제별
      - href : src/tools/tools.qmd
        text : "Tools"
      - href : src/posts/index.qmd
        text : "Posts"
      # - href : https://julia-kaeri.github.io/ClassicalMechanics.doc/
      #   text : "Classical Mechanics"
      - about.qmd
    tools:
      - icon: envelope
        href: mailto:julia.kaeri@gmail.com


  sidebar:
    - title : "Introduction to Julia"
      style : "docked"
      type : "dark"
      collapse-level : 2
      contents :
        - href: src/topics/socket.qmd

    - title: "Tools"
      collapse-level: 2
      contents:
        - src/tools/tools.qmd
        
        - href: src/tools/Asymptote/asymptote.qmd
        
        - href: src/tools/tikz/tikz.qmd
        - href: src/tools/tikz/tikz_functions.qmd
        - href: src/tools/tikz/tikz_image.qmd
        - href: src/tools/tikz/tikz_wavelet.qmd
        - href: src/tools/tikz/tikz_pde.qmd
        - href: src/tools/tikz/tikz_test.qmd

bibliography: references.bib

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    fontsize: 0.80em
    code-copy: true
    code-block-bg: true
    code-block-background: true
    code-overflow: wrap
    css: styles.css
    # html-math-method:
    #   method: mathjax
    #   url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML"
    # html-math-method: mathml
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px


