---
title: "푸리에 변환"
number-sections: true
number-depth: 2
crossref:
  chapters: false
---


## 푸리에 급수와 푸리에 변환

### 푸리에 급수

어떤 함수가 주기 $T$ 를 갖는다는 것은 모든 $t\in \mathbb{R}$ 에 대해 $f(t+T)=f(T)$ 임을 의미한다. 이 경우 $f(t)$ 는 다음과 같이 표현 할 수 있다.

::: {.callout-note appearance="simple" icon="false"}
::: {#def-fourier_series}

#### 푸리에 급수

주기 $T$ 를 갖는 연속함수 $f(t)$ 는 다음과 같은 푸리에 급수로 표현 할 수 있다.

$$
\begin{aligned}
f(t) &= \sum_{n=-\infty}^{\infty} c_n \exp \left(\dfrac{i 2\pi n}{T}t\right)\,,\\
c_n &= \dfrac{1}{T}\int_{-T/2}^{T/2} f(t) \exp \left(-\dfrac{i2\pi n }{T}t \right)\, dt\,, \qquad n\in \mathbb{Z}
\end{aligned}
$$

:::
:::


</br>

::: {#exm-fourier_exmapsion}

#### 기저함수의 직교성

임의의 정수 $m,\,n$ 에 대해 다음이 성립함을 보여라.

$$
\int_{-T/2}^{T/2} \exp \left( \dfrac{i 2\pi m}{T}t\right) \exp \left(-\dfrac{i 2\pi n}{T}t \right)\, dt = \delta_{nm}
$$

:::

</br>

#### Impulse train 의 푸리에 전개

$$
\begin{aligned}
c_n &= \dfrac{1}{\Delta T} \int_{-\Delta T/2}^{\Delta T/2} s_{\Delta T} \, \exp \left(-i \dfrac{2\pi n}{\Delta T} t\right) \, dt \\
&= \dfrac{1}{\Delta T} \sum_{k=-\infty}^\infty \int_{-\Delta T/2}^{\Delta T/2} \delta(t-k\Delta T) \exp \left(-i \dfrac{2\pi n}{\Delta T} t\right) \, dt \\
&= \dfrac{1}{\Delta T}
\end{aligned}
$$

</br>

이므로, 

$$
s_{\Delta T}(t) = \dfrac{1}{\Delta T} \sum_{n=-\infty}^{\infty} e^{i \dfrac{2 \pi n}{\Delta T}t}
$$

이다.

</br>


### 푸리에 변환


::: {.callout-note appearance="simple" icon="false"}
::: {#def-fourier_transform}

### 1차원 푸리에 변환

함수 $f(t)$ 에 대한 푸리에 변환은 $\mathfrak{F}[f(t)]$ 로 쓰고 다음과 같이 정의된다.

$$
\begin{aligned}
F(u) &:= \mathfrak{F}\left[ f(t)\right] = \int_{-\infty}^{\infty} f(t) \, e^{-2i\pi u t} \, dt,\\
f(t) &= \mathfrak{F}^{-1}[F(\mu)] = \int_{-\infty}^{\infty} F(u)\, e^{2i \pi u t} \, d\mu\,.
\end{aligned}
$$


:::
:::


::: {.callout-note appearance="simple" icon="false"}
::: {#def-fourier_transform}

### 2차원 푸리에 변환

함수 $f(x, y)$ 에 대한 푸리에 변환은 $\mathfrak{F}[f(x, y)]$ 로 쓰고 다음과 같이 정의된다.

$$
\begin{aligned}
F(u,\,v) &= \mathfrak{F} \left[f(x,\,y)\right]=\int_{-\infty}^{\infty}\int_{-\infty}^{\infty} f(x,\,y)e^{-2i\pi (ux+vy)}\, dxdy\,, \\
f (x,\,y) &= \mathfrak{F}^{-1} \left[F(u,\,v)\right] = \int_{-\infty}^{\infty} \int_{-\infty}^{\infty} F(u, v) e^{2i \pi (ux+vy)} \, dudv
\end{aligned}
$$

:::
:::


위의 경우 $F(u)$ 와 $F(u,\,v)$ 는 복소수이므로 다음과 같이 표현 할 수 있다. 

$$
F(u,\,v) = |F(u,\,v)| e^{i\Phi(u,\,v)}
$$


이 때 $|F(u,\,v)|$ 를 **푸리에 스펙트럼 (Fourier spectrum)** 이라 하고, $\Phi(u,\,v)$ 를 **위상 (phase)** 이라 한다. 또한 $P(u,\,v) =|F(u,\,v)|^2$ 를 **푸리에 파워 스펙트럼 (Fourier power spectrum)** 이라 한다.

</br>

### 푸리에 변환의 몇가지 수학적 성질

여기서 $F(u) = \mathfrak{F}[f(t)]$, $F(u, v) = \mathfrak{F}[f(x, y)]$ 이며, 2차원 푸리에 변환에 대해서 증명한다. 1차원에 대해서는 그 결과를 쉽게 유추 할 수 있다.

::: {#prp-fourier_similarity}
#### Similarity
$$
\mathfrak{F}[f(ax,\,by)] =\dfrac{1}{ab} F\left(\dfrac{u}{a},\, \dfrac{v}{b}\right)
$$
:::

::: {.proof}

$$
\begin{aligned}
\mathfrak{F}[f(ax,\,by)] &= \iint f(ax,\, by) e^{-2i\pi (ux+vy)}\,dxdy \qquad &; t=ax,\, s=by\\
&= \dfrac{1}{ab} \iint f(s,\,t) e^{-2i \pi (ut/a+vs/b)}\, dtds \\
&= \dfrac{1}{ab} F \left(\dfrac{u}{a},\, \dfrac{v}{b} \right)
\end{aligned}
$$

:::

</br>

::: {#prp-fourier_shift_property}
#### Shift property

$$
\mathfrak{F}[f(x-a,\, y-b)] = \exp (i2\pi (au+bv)) F(u,\,v)
$$

:::

::: {.proof}
$$
\begin{aligned}
\mathfrak{F}[f(x-a,\, y-b) ]&= \iint f(x-a,\, y-b) e^{-2i\pi (ux+vy)} \,dxdy \qquad &; t=x-a,\, s=y-b\\
&=\iint f(t,\,s) e^{-2i\pi (ux+vy)} e^{2i\pi (au+bv)} \, dxdy \\
&= e^{2i\pi (au+bv)}F(u,\,v)
\end{aligned}
$$

:::

</br>

::: {#prp-fourier-differential}
#### 도함수의 푸리에 변환

$$
\mathfrak{F}\left[ \dfrac{d^k}{dx^k}f(x) \right] =( 2i\pi u)^k F(u) 
$$

:::

::: {.proof}
$k=1$ 인 경우만 보이면 나머지는 쉽게 일반화 된다.$f(x)=\displaystyle \int_{-\infty}^{\infty} F(u)e^{2i\pi ux}\, du$ 이므로

$$
f'(x) =  \int_{-\infty}^{\infty}(2i\pi u) F(u)e^{2i \pi ux} \, du
$$

이다. 따라서 

$$
\mathfrak{F}[f'(x)] = (2i\pi u) F(u)
$$
이다.
:::

</br>

### 주기적 임펄스 함수의 푸리에 변환

단위 임펄스 함수(디렉 델타 함수)가 $T$ 를 주기로 반복되는 함수를 주기적 임펄스 함수라 하며 이를 $S_T(t)$ 라 하자. 이는 주기함수이므로 푸리에 급수로 표현 할 수 있으며 다음과 같다. 

$$
\begin{aligned}
S_T(t) &= \sum_{n=-\infty}^{\infty} \delta \left(t-nT \right) = \dfrac{1}{T} \sum_{n=-\infty}^{\infty} \exp \left( \dfrac{-i2n\pi t}{T}\right)
\end{aligned}
$$

단일 임펄스 함수 $\delta(\mu-\mu_0)$ 에 대한 푸리에 변환은 다음과 같다.

$$
\mathfrak{F}[\delta (\mu-\mu_0)] = \int_{-\infty}^{\infty} \delta (\mu-\mu_0) e^{2i\pi \mu t}\, d\mu = e^{2i\pi \mu_0 t}
$$

따라서,

$$
\mathfrak{F}^{-1} \left[ \delta \left( \mu-\dfrac{n}{T} \right) \right] = \exp \left( \dfrac{2in\pi t}{t} \right) \iff \mathfrak{F}\left[  \exp \left( \dfrac{2in\pi t}{t} \right) \right] =  \delta \left( \mu-\dfrac{n}{T} \right)
$$

이다. 이를 이용하면 $s_T(t)$ 의 푸리에 변환식 $S(u)=\mathfrak{F}[s_N(t)]$ 를 계산 할 수 있으며 다음과 같다.

$$
S (u) = \mathfrak{F}\left[\dfrac{1}{T} \sum_{n=-\infty}^{\infty} \exp \left( \dfrac{-i2n\pi t}{T}\right)\right] = \dfrac{1}{T} \sum_{n=-\infty}^{\infty} \mathfrak{F}\left[ \exp \left( \dfrac{-i2n\pi t}{T}\right) \right] = \dfrac{1}{T} \sum_{n=-\infty}^{\infty} \delta \left(u - \dfrac{n}{T}\right)
$$


</br>

### Convolution 의 푸리에 변환

두 함수 $f(t),\, g(t)$ 의 convolution  $f(t) \ast g(t)$ 은 다음과 같이 정의된다.

$$
f(t) \ast g(t) \equiv \int_{-\infty}^{\infty} f(\tau) g(t-\tau) \, d\tau
$$

$F(\mu)= \mathfrak{F}[f(t)],\, G(\mu)=\mathfrak{F}[g(t)]$ 라 할 때, $f(t)\otimes g(t)$ 의 푸리에 변환을 구하면,

$$
\begin{aligned}
\mathfrak{F}[f(t) \ast g(t)] &= \int_{-\infty}^{\infty} \left[ \int_{-\infty}^{\infty} f(\tau)g(t-\tau) d\tau\right] e^{-2in\pi \mu t}\, dt \\
&= \int_{-\infty}^{\infty}f(\tau) \left[  \int_{-\infty}^{\infty} g(t-\tau)e^{-2in \pi \mu t}\, dt\right] \,d\tau \\
&= \int_{-\infty}^{\infty} f(\tau) G(\mu)e^{-2in \pi \mu \tau} \, d\tau \\
&= F(\mu)G(\mu)
\end{aligned}
$$


즉 합성곱의 푸리에 변환은 푸리에 변환의 곱이다. 이를 응용하면 두 함수의 곱의 푸리에변환은 합성곱이 됨을 보일 수 있다. 즉,

$$
\mathfrak{F}[f(t)g(t)]=F(\mu)\ast G(\mu)
$$

가 된다.


일반적으로 컴퓨터에서 계산할 때 크기가 크게 다르지 않은 두 함수의 합성곱을 직접 구하는 것보다 푸리에 변환을 시킨 후 이것을 곱하고 역 푸리에 변환을 하는 것이 계산 속도가 더 빠르다. 이것은 이산 푸리에 변환의 빠른 속도 때문인데, 많은 경우 convolution의 구현은 푸리에 변환과 역푸리에 변환을 이용하여 구현된다.

</br>

###  푸리에 변환과 샘플링

임의의 연속함수 $f(t)$ 를 $T$ 를 주기로 샘플링 하였다고 하자. 그렇다면 이 샘플링 $\tilde{f}(t)$ 은 다음과 같은 식으로 표현 할 수 있다.

$$
\tilde{f}(t) = \sum_{n=-\infty}^{\infty} f(t) \delta (t-nT)
$$

이 때 $\mathfrak{I}[f(t)]= F(\mu),\, \mathfrak{I}[s_T(t)]= S(\mu)$ 라 하자 $\displaystyle S(\mu)=\dfrac{1}{T} \sum_{n=-\infty}^{\infty} \delta \left( \mu - \dfrac{n}{T}\right)$ 임은 알고 있다. 그렇다면 $\tilde{F}(\mu)=\mathfrak{I}\left[\tilde{f}(t) \right]$ 를 구하면,

$$
\begin{aligned}
\tilde{F}(\mu) & = F(\mu)\otimes S(\mu) = \int_{-\infty}^{\infty} F(\tau)S(\mu-\tau)\, d\tau \\
&= \dfrac{1}{T} \sum_{n=-\infty}^{\infty}\int_{-\infty} F(\tau) \delta \left(\mu-\tau-\dfrac{n}{T}\right)\, d\tau \\
&= \dfrac{1}{T}\sum_{n=-\infty}^{\infty} F\left( \mu - \dfrac{n}{T} \right)
\end{aligned}
$$

이다. 즉, 주기 $T$ 로 샘플링된 연속 함수 $f(t)$의 함수의 푸리에 변환은 원래 함수의 푸리에 변환 $F(\mu)$ 를 주기 $1/T$ 를 갖는 임펄스 함수로 바꾼 형태임을 알 수 있다.


</br>

## 이산 푸리에 변환 (Discrete Fourier Transformation, DFT)


### 1차원 DFT

1차원 공간상의 함수 $f$ 에 대해 $k$ 번째 에서의 값을 $f_k$ 라 하자. 그리고 이 수열을 $\langle f\rangle$ 라 하자. 즉,
$$
\langle f \rangle =(f_1,\ldots,\,f_{N})
$$

이다.

우리는 여기서 한가지 가정을 하게 되는데 $f$ 이 주기 $N$ 을 갖는다는 것이다. 즉 $f_{k+N}=f_k$ 이다. 예를 들어 $(1, 3, 2, 4)$ 에 대한 이산 푸리에 변환은 

$$
\ldots , \underline{1, 3, 2 , 4}, 1, 3,2,4, \underline{1, 3, 2,4},\ldots
$$

에 대한 푸리에 변환이라는 의미이다. (주기적으로 반복되는 것을 잘 보이게 하기 위해 밑줄로 표현하였다) 

$N$ 개의 데이터가 $N$ 의 주기로 반복되기 때문에 전체적으로 주기는 $0, 1,\ldots,\, N-1$ 



이 때 $\mathfrak{F}[f]=\langle F\rangle = (F_1,\ldots,\,F_{N-1})$ 의 $F_u$ 는 다음과 같이 구할 수 있다.

$$
F_u = \dfrac{1}{N} \sum_{k=1}^{N} f_k \exp\left(-\dfrac{i2\pi (u-1) }{N} (k-1) \right)
$$

또한 $f_k$ 는 다음과 같이 표현 할 수 있다.

$$
f_k = \sum_{u=1}^{N} F_u \exp \left(\dfrac{i2\pi (k-1)}{N} (u-1) \right)
$$

</br>





### 2차원 DFT

$$
\begin{aligned}
F_{uv} &= \dfrac{1}{MN} \sum_{j=1}^{M}\sum_{k=1}^{N} f_{jk} \exp \left[-2i\pi \left(\dfrac{(j-1)(u-1)}{M}+\dfrac{(k-1)(v-1)}{N}\right)\right] \\
f_{jk} &=  \sum_{j=1}^{M}\sum_{k=1}^{N} F_{uv} \exp \left[2i\pi \left(\dfrac{(j-1)(u-1)}{M}+\dfrac{(k-1)(v-1)}{N}\right)\right]
\end{aligned}
$$


</br>

</br>

### 고속 푸리에 변환

이산 푸리